# Documentation: https://haobogu.github.io/rmk/keyboard_configuration.html
[keyboard]
name = "Pabile60"
product_name = "Pabile60"
vendor_id = 0x8065
product_id = 0x4643
manufacturer = "Pabile"
#chip = "rp2040"
#12/12 Error: "The specified chip/board 'pi_pico_w' does not exist in the template repo"
board = "pi_pico_w"

[matrix]
# Input and output pins are mandatory
row_pins = ["PIN_31", "PIN_29", "PIN_27", "PIN_26", "PIN_25", "PIN_24", "PIN_22", "PIN_11", "PIN_14", "PIN_15"]
col_pins = ["PIN_21", "PIN_2", "PIN_6", "PIN_7", "PIN_9", "PIN_10"]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = true

[layout]
cols = 6
rows = 10
layers = 1
matrix_map = """
(0,0) (0,1) (0,2) (0,3) (0,4) (0,5) 
(5,0) (5,1) (5,2) (5,3) (5,4) (5,5) 
(1,0) (1,1) (1,2) (1,3) (1,4) (1,5) 
(6,0) (6,1) (6,2) (6,3) (6,4) (6,5) 
(2,0) (2,1) (2,2) (2,3) (2,4) (2,5) 
(7,0) (7,1) (7,2) (7,3) (7,4) (7,5) 
(3,0) (3,1) (3,2) (3,3) (3,4) (3,5) 
(8,0) (8,1) (8,2) (8,3) (8,4) (8,5) 
(4,0) (4,1) (4,2) (4,3) (4,4) (4,5) 
(9,0) (9,1) (9,2) (9,3) (9,4) (9,5) 
"""
keymap = [
    [
        ["Grave",  "Kc1",  "Kc2",  "Kc3",   "Kc4",       "Kc5"],   ["Kc6",    "Kc7",    "Kc8",   "Kc9",  "Kc0",       "Delete"],
        ["Tab",    "Q",    "W",    "E",     "R",         "T"],     ["Y",      "U",      "I",     "O",    "P",         "Minus" ],
        ["Escape", "A",    "S",    "D",     "F",         "G"],     ["H",      "J",      "K",     "L",    "Semicolon", "Quote" ],
        ["LShift", "Z",    "X",    "C",     "V",         "B"],     ["N",      "M",      "Comma", "Dot",  "Slash",     "RShift"],
        ["LCtrl",  "LGui", "LAlt", "MO(1)", "Backspace", "Space"], ["MO(2)",  "MO(3)",  "RAlt",  "RGui", "RCtrl",     "Escape"]
    ]
]

[light]
# All light pins are high-active by default, uncomment if you want it to be low-active
# capslock.pin = "PB2"
# capslock.low_active = true
# scrolllock.pin = "PA3"
# scrolllock.low_active = true
# Just ignore if no light pin is used for it
# numslock.pin = "PA5"
# numslock.low_active = true

[storage]
# Storage feature is enabled by default
# enabled = false

[ble]
enabled = true
